<?php

namespace api\models;

use api\models\ProductImage;
use soft\db\ActiveQuery;

class Product extends \common\modules\product\models\Product
{
    /**
     * @return array|string[]
     */
    public function fields()
    {
        $key = self::generateFieldParam();

        if (isset(self::$fields[$key])) {
            return self::$fields[$key];
        }

        return [
//            'id',
            'slug',
            'name',
            'description',
            'category_id',
            'sub_category_id',
            'percentage',
            'published_at',
            'expired_at',
            'price',
            'discount_price' => 'sum',
            'brand_id',
            'content',
            'country_id',
            'is_stock',
            'most_popular',
            'image',
        ];
    }

    /**
     * @return ActiveQuery
    */
    public function getImage()
    {
        return $this->hasOne(ProductImage::class, ['product_id' => 'id']);
    }

    /**
     * @return ActiveQuery
    */
    public function getImages()
    {
        return $this->hasMany(ProductImage::class, ['product_id' => 'id']);
    }

    /**
     * @return float|int
     */
    public function getSum(): float|int
    {
        return ($this->price * $this->percentage) / 100;
    }

    public function getSizes()
    {
        return parent::getSizes(); // TODO: Change the autogenerated stub
    }
}